### ISSUE TITLE
Present an alert if the client has installed the Debug/Trace in WordPress instead of in the ds-plugins folder

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/debug-trace#2]
STEPS TO REPRODUCE:

    Download plugin and install via WordPress.

RESULT:

An error is produced
EXPECTED RESULT:

An alert instructing them to install it in OS path \ ds-plugins

![screen shot 2018-06-12 at 7 52 10 am](https://user-images.githubusercontent.com/1041421/41298121-8aa5ef40-6e15-11e8-87d6-4c4cf47d1e90.jpg)

**Comment by davejesch** [comment]
added message

**Comment by GreggFranklin** [comment]
( ! ) Fatal error: Uncaught Error: Using $this when not in object context in /Users/GreggFranklin/Documents/Websites/test99.dev.cc/wp-content/plugins/debug-trace-master/debug-trace.php on line 15
( ! ) Error: Using $this when not in object context in /Users/GreggFranklin/Documents/Websites/test99.dev.cc/wp-content/plugins/debug-trace-master/debug-trace.php on line 15
Call Stack
#	Time	Memory	Function	Location
1	0.0171	666912	{main}( )	.../plugins.php:0
2	0.3631	24595976	plugin_sandbox_scrape( )	.../plugins.php:172
3	0.3633	24600128	include( '/Users/GreggFranklin/Documents/Websites/test99.dev.cc/wp-content/plugins/debug-trace-master/debug-trace.php' )	.../plugin.php:1897

**Comment by davejesch** [comment]
fixed callback reference

**Comment by GreggFranklin** [comment]
Issue resolved
