### ISSUE TITLE
In combination with DS-CLI, the wp-config.php file is output on the command line

### ISSUE THREAD

**Issue by Steveorevo** [ServerPress/debug-trace#4]
#### STEPS TO REPRODUCE: 
1. Start DesktopServer and enable both Debug & Trace, and DS-CLI
2.  Open a DS-CLI prompt for a given website
3. Type wp

#### RESULT: 
The output of the wp-config.php file and errors appear before the WP-CLI help information.

Occurs on both Mac & Windows
Screenshots at https://github.com/ServerPress/ds/issues/174

**Comment by Steveorevo** [comment]
Fixed in 13b70bd06340a2aafc1215635d4f50948a7cb9fc

**Comment by GreggFranklin** [comment]
Issue resolved
