### ISSUE TITLE
Starting Trace only works when DS-CLI is active

### ISSUE THREAD

**Issue by davejesch** [ServerPress/debug-trace#5]
#### STEPS TO REPRODUCE: 
1. Start DS with only Debug/Trace active
2. Click the "Start Debug/Trace Window" from the localhost Tools menu

#### RESULT: 
Trace window is not launched

#### EXPECTED RESULT: 
Trace window launched

This is caused because the click handler for the "Start Debug/Trace Window" menu item requires jQuery to be loaded on the page. Debug/Trace needs to add this to the header.

**Comment by GreggFranklin** [comment]
*Option Move the script call to the top rather than the bottom.
<script src="http://localhost/js/jquery.min.js"></script>

**Comment by GreggFranklin** [comment]
This issue is resolved
